### ISSUE TITLE
Backbone RL algorithm

### ISSUE THREAD

**Issue by zichunxx** [mazpie/redundancy-action-spaces#2]
Hi @mazpie!

The vanilla SAC is cited in your paper to finish the training process. But from the code, I think the backbone RL algo is more like `drq` with the distributional critic. If what I thought is correct, is this the first combination of `drq` and distributional critic by you or someone else? Could you give some references about this kind of combination? I want to learn some details about the advantages of the distributional critic. 

Thanks in advance for your guidance.

**Comment by mazpie** [comment]
Hi @zichunxx,

the backbone of the RL algorithm is [SAC](https://arxiv.org/abs/1801.01290).  
The following modifications are also applied (not included in the paper due to the maximum number of page limitation):
- random shift augmentations (similar to: https://arxiv.org/abs/2004.13649)
- distributional critic (recent studies show this improves training stability and performance: https://arxiv.org/abs/2403.03950)
- reward and return normalization (find one example here, though it's not exactly the same as our scaling: https://arxiv.org/abs/2105.05347)

Hope this helps!

**Comment by zichunxx** [comment]
Sincerest thanks! This helps me a lot.

**Comment by zichunxx** [comment]
Hi @mazpie! Sorry for reopening this issue.

I have read the second paper and tried to find the theoretical foundation or implementation details about the `from_categorical` and `to_categorical` functions in your code. The categorical distribution method is different from Two-hot, C51, and histogram. It seems like another kind of variant based on the above methods. I tried to tune the relevant parameters, like [limit](https://github.com/mazpie/redundancy-action-spaces/blob/7e7d717819f1217ad1cfe9841b08ae104174904b/rl/agent/mf_utils.py#L111) and [offset](https://github.com/mazpie/redundancy-action-spaces/blob/7e7d717819f1217ad1cfe9841b08ae104174904b/rl/agent/mf_utils.py#L111), to reach higher performance. 

Could you provide more information focusing on the above realization? Thanks!

**Comment by mazpie** [comment]
Hi @zichunxx,

the implementation you find here is something in between the method applied in MuZero (see Appendix F here: https://arxiv.org/abs/1911.08265) and in DreamerV3 (equation 8 here: https://arxiv.org/abs/2301.04104v1).

In order, the returns are:
- rescaled, using the returns' running stddev
- transformed using the hyperbolic function
- discretized into a two-hot distribution

I found this strategy to work effectively across all the tasks (having different scales of rewards and returns).

Hope this helps!
